import "../styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import Script from "next/script";
import { AuthProvider } from "../context/reducers/AuthProvider";
import Layout from "../components/Layout";
import { useEffect } from "react";
import "aos/dist/aos.css";
import AOS from "aos";
import { auth } from "../firebase";

function MyApp({ Component, Props }) {
  useEffect(() => {
    AOS.init();
  });

  return (
    <>
      <Head>
        <title>Resto | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/resto.png" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/fe2e019d14.js"
        crossOrigin="anonymous"
      ></Script>

      <AuthProvider>
        <Layout>
          <Component {...Props} />
        </Layout>
      </AuthProvider>
    </>
  );
}

export default MyApp;
