import Head from "next/head";
import { useEffect, useState } from "react";

export default function About(props) {
  const [prop, setprop] = useState([]);
  useEffect(() => {
    setprop(props.data);
  }, []);

  return (
    <div>
      <Head>
        <title>Resto | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/resto.png" />
      </Head>

      <div className="about">
        {prop &&
          prop.map((data, i) => {
            return <div key={i}>{data.title}</div>;
          })}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const fetching = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await fetching.json();

  return {
    props: {
      data,
    },
  };
}
