import Head from "next/head";
import Script from "next/script";

export default function Home(s) {
  return (
    <div>
      <Head>
        <title>Resto | Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/resto.png" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/fe2e019d14.js"
        crossOrigin="anonymous"
      ></Script>

      <div className="contacts">
        <h1>Contacts Section</h1>
      </div>
    </div>
  );
}
