import Head from "next/head";
import Banner from "../components/Home/banner";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Resto | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/resto.png" />
        <script
          src="https://kit.fontawesome.com/fe2e019d14.js"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <div className="home">
        <Banner />
      </div>
    </div>
  );
}
