import Head from "next/head";
import Script from "next/script";
import Banner from "../components/Home/banner";
import FeaturedDish from "../components/Home/featureddish";
import SmallBanner from "../components/Home/smallbanner";
import Testimonial from "../components/Home/testimonial";
import { useSession, signIn, signOut } from "next-auth/client";
export default function Home() {
  const [session, loading] = useSession();
  console.log(session);
  return (
    <div>
      <Head>
        <title>Resto | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/resto.png" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/fe2e019d14.js"
        crossOrigin="anonymous"
      ></Script>
      <div className="home">
        <Banner />

        <FeaturedDish />
        <SmallBanner />
        <Testimonial />
      </div>
    </div>
  );
}
