import Head from "next/head";
import Script from "next/script";
import { Card, Row, Col } from "react-bootstrap";
import bg from "../public/assets/banner2.jpg";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useAuthContext } from "../context/AuthProvider";
import { db } from "../firebase";
import { useOrderContext } from "../context/orderContext";
// component
export default function Home() {
  const { showaddmenumodal, currentUser, showplaceorder } = useAuthContext();
  const { setIsOrder } = useOrderContext();
  const [menus, setMenus] = useState();
  useEffect(() => {
    const fetch = async () => {
      await db.collection("menus").onSnapshot((snap) => {
        setMenus(snap.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
      });
    };
    fetch();
  }, []);

  return (
    <div>
      <Head>
        <title>Resto | Menus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/resto.png" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/fe2e019d14.js"
        crossOrigin="anonymous"
      ></Script>
      <div className="menus">
        <Image
          src={bg}
          layout="fill"
          objectFit="cover"
          objectPosition="center"
        />

        <div className="search">
          <form>
            <input type="search" placeholder="search dish..." />
            <button>
              <i className="fas fa-search"></i>
            </button>
          </form>
        </div>
        {currentUser && currentUser.email === "jonathan.digay1@gmail.com" && (
          <div className="addMenuBtn">
            <i
              className="fas fa-plus-circle"
              onClick={() => showaddmenumodal()}
            ></i>
          </div>
        )}

        <div className="menus-food">
          <Row>
            {menus &&
              menus.map((menu, index) => {
                return (
                  <Col
                    xs={6}
                    sm={6}
                    md={4}
                    lg={3}
                    xxl={2}
                    className="d-flex justify-content-center"
                    key={index}
                  >
                    <Card>
                      <Card.Body>
                        <Image src={menu.foodPhoto} width="300" height="300" />
                      </Card.Body>
                      <Card.Title>{menu.foodName}</Card.Title>
                      <Card.Footer>
                        <p>{`P${menu.foodPrice}`}</p>
                        <button
                          onClick={() => {
                            showplaceorder();
                            setIsOrder(menu);
                          }}
                        >
                          Place order
                        </button>
                      </Card.Footer>
                      {currentUser &&
                        currentUser.email == "jonathan.digay1@gmail.com" && (
                          <button
                            onClick={() => {
                              const deletion = async () => {
                                try {
                                  await db
                                    .collection("menus")
                                    .doc(menu.id)
                                    .delete();
                                } catch (e) {
                                  console.log(e);
                                }
                              };
                              deletion();
                            }}
                          >
                            Delete
                          </button>
                        )}
                    </Card>
                  </Col>
                );
              })}
          </Row>
        </div>
      </div>
    </div>
  );
}
